@startuml
'https://plantuml.com/class-diagram

class FBPostVerification {
' Атрибуты
- signature: byte[]
- dateOfSignature: date
- location: GPS_coordinates
- uniformResourceIdentifier: String
- user: String
' Методы:
+ getSignature(file, DataBase, screenshot: JPG): byte[]
+ getDate(file, DataBase, screenshot: JPG): byte[]
+ getLocation(file, DataBase, screenshot: JPG): byte[]
+ getOwner(file, DataBase, screenshot: JPG): String
}

class AggregateSignature{
- signature: byte[]
- user
+ AggregateSignature(FBPostVerification)
}
AggregateSignature::AggregateSignature ..> FBPostVerification
AggregateSignature::user ..> FBPostVerification::user

class AllSignaturesAtSomeDate{
- allSignaturesAtSomeDate: ListOfString
- appendAggregateSignature(AggregateSignature)
- saveToFile(allSignaturesAtSomeDate): File
}

File File {
}

File <.. AllSignaturesAtSomeDate

class Signature{
- Signature: byte[]
- calculateSignature(File)
- putToBlockChain(Signature)
}

class PlanerOfPutInBlockChain{
+ bySchedule(Signature, Rules)
+ byDemand(Signature, Rules, payment)
}
PlanerOfPutInBlockChain::bySchedule <.. Rules
PlanerOfPutInBlockChain::bySchedule <.. Signature

class Rules{
+ rules1
+ rules2
+ AccessLevels
+ typeOfBlockChain
}


Signature::calculateSignature <.. File

AllSignaturesAtSomeDate::appendAggregateSignature ..> AggregateSignature

@enduml